In [14]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_csv('CSV/conti_hope.csv')
data = data[400:] 
data

,Companies,Industries,Headquarters,Affected_Date
400,Beler Holdings Inc,Wholesale,"Mississauga, ONTARIO",Jan-01
401,"Cambria County, Pennsylvania",Local Government,"Philadelphia, PA",Jan-01
402,New Light Christian Christian Center,Religious Organisations,"Houston, TX",Jan-01
403,ThyssenKrupp Holding,Mechanical Or Industrial Engineering,"Essen, Germany",Jan-01
404,Allfasteners,Industrial Manufacturing,"Medina, OH",Jan-01
...,...,...,...,...
472,CORE Information Technology Consultants Ltd.,IT Service,"London, United Kingdom",Jan-01
473,Hi-Line Moving Services,Commercial Equipment Repair & Maintenance,"Dallas, TX",Jan-01
474,Whistl.UK,Logistics & Supply Chain,"Marlow, United Kingdom",Jan-01
475,Omnetics Connector Corporation,Electrical & Electronic Manufacturing,"Fridley, MN",Jan-01
476,LABORATOIRES EXPANSCIENCE,Biotech & Pharmaceutical,"Courbevoie, France",Jan-01

In [18]:
pip install geopy

Collecting geopy
  Using cached https://files.pythonhosted.org/packages/e1/e1/45f25e3d3acf26782888f847de7c958a2807a039210fb1016cc3fb9555c4/geopy-2.2.0-py3-none-any.whl
Collecting geographiclib<2,>=1.49 (from geopy)
  Using cached https://files.pythonhosted.org/packages/df/60/d1d4c4944f9726228faa80fbe2206c8ddfd9757791b2de2facb8818c5d74/geographiclib-1.52-py3-none-any.whl
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-1.52 geopy-2.2.0
Note: you may need to restart the kernel to use updated packages.

In [26]:
from geopy.geocoders import Nominatim 

geolocator = Nominatim(user_agent = "geoapiExercises")
num = 0
country_list = []

for city in data['Headquarters']:
    place, (lat, lng) = geolocator.geocode(city)
    country = place.split()[-1]
    print(country)
    country_list.append(country)
    
data['Country'] = country_list

Canada
States
States
Deutschland
States
States
States
States
States
States
States
States
States
States
States
States
States
States
States
Canada
States
States
States
States
States
Kingdom
Kingdom
Singapore
States
Canada
Deutschland
States
States
States
States
Kingdom
States
States
States
Canada
Canada
Kingdom
States
States
States
States
States
States
Kingdom
States
States
States
States
States
States
States
Canada
Colombia
States
Canada
States
States
States
States
States
States
Canada
Deutschland
India
States
States
States
Kingdom
States
Kingdom
States
France

In [29]:
data

,Companies,Industries,Headquarters,Affected_Date,Country
400,Beler Holdings Inc,Wholesale,"Mississauga, ONTARIO",Jan-01,Canada
401,"Cambria County, Pennsylvania",Local Government,"Philadelphia, PA",Jan-01,States
402,New Light Christian Christian Center,Religious Organisations,"Houston, TX",Jan-01,States
403,ThyssenKrupp Holding,Mechanical Or Industrial Engineering,"Essen, Germany",Jan-01,Deutschland
404,Allfasteners,Industrial Manufacturing,"Medina, OH",Jan-01,States
...,...,...,...,...,...
472,CORE Information Technology Consultants Ltd.,IT Service,"London, United Kingdom",Jan-01,Kingdom
473,Hi-Line Moving Services,Commercial Equipment Repair & Maintenance,"Dallas, TX",Jan-01,States
474,Whistl.UK,Logistics & Supply Chain,"Marlow, United Kingdom",Jan-01,Kingdom
475,Omnetics Connector Corporation,Electrical & Electronic Manufacturing,"Fridley, MN",Jan-01,States
476,LABORATOIRES EXPANSCIENCE,Biotech & Pharmaceutical,"Courbevoie, France",Jan-01,France

In [32]:
data.to_csv('CSV/Conti_400-476.csv')